Lemur/urls.py
from django.contrib import admin
from django.urls import path, include
from bluecrane import views
from users import views as users_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from tinymce import HTMLField

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    #path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('', include('bluecrane.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bluecrane/urls.py
from django.urls import path
from django.views.generic import View 
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
from . import views

app_name = 'bluecrane'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('coming/', views.coming_soon, name='coming'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    #path('signup/', views.SignUp.as_view(), name='signup'),
]

bluecrane/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from tinymce import HTMLField

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = HTMLField('Content', null=True) 
    date_posted = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'pk': self.pk})

    def summary(self):
        return self.content[:50]

    def __str__(self):
        return self.title

class Author(models.Model):
    first_name=models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    headline = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='authors')

    def __str__(self):
        return last_name

users/models.py
from django.db import models
from django.contrib.auth.models import User 
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    emails = forms.EmailField()

    class Meta:
        model = User
        fields = ['username']

class UserUpdateForm(forms.ModelForm):
     emails = forms.EmailField()
     class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

bluecrane/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Post, Author
from django.views.generic import TemplateView, DetailView, ListView, DeleteView, UpdateView, CreateView, View
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'bluecrane/home1.html', context)

def about(request):
    return render(request, 'bluecrane/about1.html', {'title': 'About'})


def coming_soon(request):
    return render(request, 'bluecrane/coming_soon.html')

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'bluecrane/detail.html'

class PostListView(ListView):
    model = Post
    template_name = 'bluecrane/home1.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

class UserPostListView(ListView):
    model = Post
    template_name = 'bluecrane/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
         u_form = UserUpdateForm(instance=request.user)
         p_form = ProfileUpdateForm(instance=request.user.profile)


    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html')

bluecrane/templates/bluecrane/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>BL Free</title>
		<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block css %}
	<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	<link rel="stylesheet" href="{% static 'css/style-rtl.css' %}" />
	<link href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template specific stylesheets-->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="{% static 'lib/animate.css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'lib/components-font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/et-line-font/et-line-font.css' %}" rel="stylesheet">
    <link href="{% static 'lib/flexslider/flexslider.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owl.carousel/dist/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owl.carousel/dist/assets/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/magnific-popup/dist/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'lib/simple-text-rotator/simpletextrotator.css' %}" rel="stylesheet">
    <!-- Main stylesheet and color file-->
    <link href="{#}" rel="stylesheet">
	<link id="color-scheme" href="{% static 'css/colors/default.css' %}" rel="stylesheet">
	

    {% endblock %}
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="index.html" class="logo"><strong>Free Programming</strong></a>
					<a href="{% url 'bluecrane:home' %}">Python</a>
					<a href="{% url 'bluecrane:coming' %}">Elasticsearch</a>
					<a href="{% url 'bluecrane:coming' %}">Bitbucket</a>
					<a href="{% url 'bluecrane:coming' %}">Javascript</a>
					<a href="{% url 'bluecrane:about' %}">Redis</a>
					<a href="{% url 'register' %}">Sign Up</a>
					<form class="form-inline my-2 my-lg-0">
							<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
							<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
					</form>
					<nav id="nav">
					</nav>
					<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
				</div>
			</header>

		<!-- Banner -->
			<section id="banner" style="background-image:url({#}">
				<div class="inner">
					</div>
      {% block content %}

      {% endblock %}

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h3>Get in touch</h3>

					<form action="#" method="post">

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
					</form>

					<div class="copyright">
						&copy; 2018 Designed by The BL Project, All Rights Reserved <a href="www.theblproject.com"></a>. 
					</div>

				</div>
			</footer>

      {% block JavaScripts %}
		<!-- Scripts -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/skel.min.js' %}"></script>
	<script src="{% static 'js/util.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'lib/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/wow/dist/wow.js' %}"></script>
    <script src="{% static 'lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js' %}"></script>
    <script src="{% static 'lib/isotope/dist/isotope.pkgd.js' %}"></script>
    <script src="{% static 'lib/imagesloaded/imagesloaded.pkgd.js' %}"></script>
    <script src="{% static 'lib/flexslider/jquery.flexslider.js' %}"></script>
    <script src="{% static 'lib/owl.carousel/dist/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/smoothscroll.js' %}"></script>
    <script src="{% static 'lib/magnific-popup/dist/jquery.magnific-popup.js' %}"></script>
    <script src="{% static 'lib/simple-text-rotator/jquery.simple-text-rotator.min.js' %}"></script>
    <script async="" defer="" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDK2Axt8xiFYMBMDwwG1XzBQvEbYpzCvFU"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
      {% endblock %}
	</body>
</html>

bluecrane/templates/bluecrane/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--  
    Document Title
    =============================================
    -->
    <title>The LM Foundation</title>
    <!--  
    Favicons
    =============================================
    -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favicons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!--  
    Stylesheets
    =============================================
    
    -->
    <!-- Default stylesheets-->
    {% block css %}
    <link href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Template specific stylesheets-->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="{% static 'lib/animate.css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'lib/components-font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/et-line-font/et-line-font.css' %}" rel="stylesheet">
    <link href="{% static 'lib/flexslider/flexslider.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owl.carousel/dist/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owl.carousel/dist/assets/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/magnific-popup/dist/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'lib/simple-text-rotator/simpletextrotator.css' %}" rel="stylesheet">
    <!-- Main stylesheet and color file-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link id="color-scheme" href="{% static 'css/colors/default.css' %}" rel="stylesheet">

    {% endblock %}
  </head>
  <body data-spy="scroll" data-target=".onpage-navigation" data-offset="60">
    <main>
      <nav class="navbar navbar-custom navbar-fixed-top bg-light" role="navigation">
        <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="{% url 'bluecrane:home' %}">The LM Foundation</a>
          </div>
          <div class="collapse navbar-collapse" id="custom-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown"><a href="{% url 'bluecrane:home' %}">Home</a>
              <li class="dropdown"><a href="{% url 'bluecrane:coming' %}">Scholarships</a>
              <li class="dropdown"><a href="{% url 'bluecrane:about' %}">About Us</a>
              <li class="dropdown"><button class="btn btn-danger btn-circle"><a href="{% url 'register' %}">Donate</a></button>
      </div>
    </ul>
  </div>
  </div>
  </div>
</nav>
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
      
      {% endblock %}
        <div class="module-small bg-dark"> 
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <div class="widget">
                  <h5 class="widget-title font-alt">Our Mission</h5>
                  <p>We want to contribute to the transformation of individual and family lives through scholarship and continuous engagement.</p>
                  <p>Phone: +1 432 305-6108</p>
                  <p>Email:<a href="#">bandini@theblproject.com</a></p>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
        <hr class="divider-d">
        <footer class="footer bg-dark">
          <div class="container">
            <div class="row">
              <div class="col-sm-6">
                <p class="copyright font-alt">&copy; 2018&nbsp;<a href="{% url 'bluecrane:about' %}">Designed by Lawrence Mainja for The BL Project</a>, All Rights Reserved</p>
              </div>
              <div class="col-sm-6">
                <div class="footer-social-links"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-dribbble"></i></a><a href="#"><i class="fa fa-skype"></i></a>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </div>
      <div class="scroll-up"><a href="#totop"><i class="fa fa-angle-double-up"></i></a></div>
    </main>
    <!--  
    JavaScripts
    =============================================
    -->
    {% block JavaScripts %}
    <script src="{% static 'lib/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/wow/dist/wow.js' %}"></script>
    <script src="{% static 'lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js' %}"></script>
    <script src="{% static 'lib/isotope/dist/isotope.pkgd.js' %}"></script>
    <script src="{% static 'lib/imagesloaded/imagesloaded.pkgd.js' %}"></script>
    <script src="{% static 'lib/flexslider/jquery.flexslider.js' %}"></script>
    <script src="{% static 'lib/owl.carousel/dist/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/smoothscroll.js' %}"></script>
    <script src="{% static 'lib/magnific-popup/dist/jquery.magnific-popup.js' %}"></script>
    <script src="{% static 'lib/simple-text-rotator/jquery.simple-text-rotator.min.js' %}"></script>
    <script async="" defer="" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDK2Axt8xiFYMBMDwwG1XzBQvEbYpzCvFU"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}
  </body>
</html>

bluecrane/templates/bluecrane/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %} Home {% endblock title %} Live Stream</title>
  <meta charset="=utf-8"/>
  {% load static %}
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type='text/css'/>
  <link href="{% static "css/live.css" %}" rel="stylesheet"/> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> 

<header>
    <div class="mkt-nav">
        <li><a href="{% url 'Home' %}">Home</a></li>  <li><a href="{% url 'about' %}">About</a></li>  <li><a href="{% url 'sermon' %}">Sermon</a></li>  <li><a href="{% url 'login' %}">Login</a></li>
    </div>
 </header>

{% block head_favicon %}
    <link rel="icon" type="image/png"
          href="{% static "images/favicon.ico" %}">
{% endblock head_favicon %}

{% block head_meta %}
    {% block head_meta_charset %}
        <meta http-equiv="Content-Type"
              content="text/html; charset=utf-8" />
    {% endblock head_meta_charset %}
    {% block head_meta_contentlanguage %}
        <meta http-equiv="Content-Language" value="en-US" />
    {% endblock head_meta_contentlanguage %}
    {% block head_meta_viewport %}
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">
    {% endblock head_meta_viewport %}
{% endblock head_meta %}
{% block head_css %}
    {% block head_css_site %}
        <link href="{% static "css/bootstrap.min.css" %}"
              rel="stylesheet" media="screen">
        <link href="{% static "css/live.css" %}"
              rel="stylesheet" media="screen">
    {% endblock head_css_site %}
    {% block head_css_section %}{% endblock head_css_section %}
    {% block head_css_page %}{% endblock head_css_page %}
{% endblock head_css %}

</head>

<body> 
        
{# The Document Body #}
<div id="site-wrapper">
    {% block content %}
        if you see this, something is wrong!
    {% endblock content %}
</div>
{# The Footer #}

<div class="footer">
    <div class="container">
        <p>Copyright 2018 @ Black Lemur. All Rights Reserved.</p>
    </div>
</div>
</body>



{% block footer_javascript %}
        {% block footer_javascript_site %}
            <script src="{% static "js/jquery.min.js" %}"></script>
            <script src="{% static "js/bootstrap.min.js" %}"></script>
            <script src="{% static "js/live.js" %}"></script>
            <script src="{% static "js/navbar.js" %}"></script>
        {% endblock footer_javascript_site %}
        {% block footer_javascript_section %}{% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>

bluecrane/templates/bluecrane/coming_soon.html
{% extends 'bluecrane/base.html' %}
{% load static %}
{% block content %}
<section class="home-section home-parallax home-fade home-full-height" id="home">
        <div class="hero-slider">
          <ul class="slides">
            <li class="bg-dark-30 bg-dark" style="background-image:url({% static 'images/gold.jpg' %});">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1">Pangol</div>
                  <div class="font-alt mb-40 titan-title-size-2">A Mineral Deposit Tracking App</div><a class="section-scroll btn btn-border-w btn-round" href="#about">Learn More</a>
                </div>
              </div>
            </li>
            <li class="bg-dark-30 bg-dark" style="background-image:url({% static 'images/classic-clothes.jpg' %});">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1">Blue Crane Fashion</div>
                      <div class="font-alt mb-40 titan-title-size-2">A Luxury Clothing App</div><a class="btn btn-border-w btn-round" href="#">Learn More</a>
                </div>
              </div>
            </li>
            <li class="bg-dark-30 bg-dark" style="background-image:url({% static 'images/book-stack-books.jpg' %});">
              <div class="titan-caption">
                <div class="caption-content">
                  <div class="font-alt mb-30 titan-title-size-1">The LM Foundation</div>
                  <div class="font-alt mb-40 titan-title-size-2">A Scholarship App</div><a class="section-scroll btn btn-border-w btn-round" href="#about">Learn More</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </section>
{% endblock %}

bluecrane/templates/bluecrane/comments.html
{% extends 'posts/base.html' %}
{% load static %}

{% block content %}
<h3>New Comment</h3>
<form method="POST" class="post-form">
   {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Send</button>
</form>

{% endblock content %}

bluecrane/templates/bluecrane/detail.html
{% extends 'bluecrane/base.html' %}
{% load static %}
{% block content %}
<section class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="row multi-columns-row post-columns">
            <div class="post">
              <div class="post-header font-alt">
                <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
                  <div class="media-body">
                    <div class="article-metadata">
                       <a class="mr-2" href="{% url 'bluecrane:user-posts' object.author.username %}">{{ object.author }}</a>
                         <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
                          {% if object.author == user %}
                           <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bluecrane:post-update' object.id %}">Update</a>
                            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'bluecrane:post-delete' object.id %}">Delete</a>
                         </div>
                       {% endif %}
                      </div>
                    <h2 class="article-title">{{ object.title }}</h2>
                    <p class="article-content">{{ object.content|safe }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
{% endblock content %}

bluecrane/templates/bluecrane/user_posts.html
{% extends "bluecrane/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'bluecrane:user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'bluecrance:detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

users/templates/users/logged_out.html
{% extends "bluecrane/base.html" %}

{% block content %}
<h3>You have been logged out.</h3>
<div class="border-top pt-3">
    <small class="text-muted">
        <a class="ml-2" href="{% url 'login' %}">Log In Again</a>
    </small>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "bluecrane/base.html" %}
{% block content %}

<h1>The password has been changed!</h1>
<p><a href="{% url 'login' %}">log in again?</a></p>

{% endblock %}